<?php

namespace Omnipay\ECPay\Message;

use Exception;
use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Common\Message\NotificationInterface;
use Omnipay\ECPay\Traits\HasECPay;

class CompletePurchaseResponse extends AbstractResponse implements NotificationInterface
{
    use HasECPay;

    public function isSuccessful()
    {
        return $this->valid() && $this->getCode() === '1';
    }

    /**
     * Response Message.
     *
     * @return null|string A response message from the payment gateway
     */
    public function getMessage()
    {
        return $this->data['RtnMsg'];
    }

    /**
     * Response code.
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode()
    {
        return $this->data['RtnCode'];
    }

    /**
     * Gateway Reference.
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference()
    {
        return $this->data['TradeNo'];
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['MerchantTradeNo'];
    }

    public function getTransactionStatus()
    {
        return $this->isSuccessful() ? self::STATUS_COMPLETED : self::STATUS_FAILED;
    }

    protected function checkoutFeedback()
    {
        $this->createECPay($this->request)->CheckOutFeedback();

        return true;
    }

    /**
     * @return bool
     */
    private function valid()
    {
        try {
            return $this->checkoutFeedback();
        } catch (Exception $e) {
            return false;
        }
    }
}
